# Generated by Django 5.2.15 on 2026-06-22 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('version', models.CharField(max_length=30)),
                ('framework', models.CharField(choices=[('OPENCV', 'OpenCV'), ('YOLO', 'Ultralytics YOLO'), ('PYTORCH', 'PyTorch'), ('ONNX', 'ONNX Runtime')], default='OPENCV', max_length=20)),
                ('model_type', models.CharField(default='object_detection', max_length=80)),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('VALIDATING', 'Validating'), ('READY', 'Ready'), ('RETIRED', 'Retired'), ('FAILED', 'Failed')], default='READY', max_length=20)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'name', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name', 'version'), name='unique_model_version')],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('version', models.CharField(default='1.0.0', max_length=30)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'name', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name', 'version'), name='unique_recipe_version')],
            },
        ),
    ]
