# Generated by Django 5.2.15 on 2026-06-22 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('ERROR', 'Error'), ('OFFLINE', 'Offline')], default='IDLE', max_length=20)),
                ('plc_mode', models.CharField(choices=[('MOCK', 'Mock'), ('SOFTWARE', 'Software Trigger'), ('HARDWARE', 'Hardware Trigger')], default='MOCK', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Laser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('SCANNING', 'Scanning'), ('ERROR', 'Error'), ('OFFLINE', 'Offline')], default='READY', max_length=20)),
                ('mock_enabled', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lasers', to='machines.machine')),
            ],
            options={
                'ordering': ['machine', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(default='SYSTEM', max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='machines.machine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('station', models.CharField(default='Inspection Station', max_length=80)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('CAPTURING', 'Capturing'), ('ERROR', 'Error'), ('OFFLINE', 'Offline')], default='READY', max_length=20)),
                ('exposure_us', models.PositiveIntegerField(default=2500)),
                ('mock_enabled', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='machines.machine')),
            ],
            options={
                'ordering': ['machine', 'name'],
            },
        ),
    ]
